services:
  postgres:
    image: postgres:15-alpine
    container_name: bankbot-database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bankbot
      - POSTGRES_PASSWORD=bankbot
      - POSTGRES_DB=bankbot
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3